### ISSUE TITLE
Flyout system bugged with any keybind using control modifier

### ISSUE THREAD

**Issue by Bonkeybee** [kurapica/ShadowDancer#1]
The action bar flyout will activate if you have a key binding or macro set to use the ctrl modifier while also left clicking right at the same moment as pressing the keybind anywhere on the screen.

Example macro bound on the letter "c":
```
#showtooltip 
/cast [nomod] Demoralizing Shout; [mod:shift] Battle Shout; [mod:ctrl] Commanding Shout
/cast Bloodrage
```
Hold ctrl, press "c" and left click at the same time repeatedly.
![shdbug](https://user-images.githubusercontent.com/9619823/143139664-4057554b-a3fb-4cb8-9c68-3c8375a1c241.gif)

**Comment by kurapica** [comment]
Add a mouse over check in r024, should fix it in most cases
